<?php
// config.php (Generated by installer)
session_start();

define('DB_HOST', 'sql313.infinityfree.com');
define('DB_NAME', 'if0_40879094_pos');
define('DB_USER', 'if0_40879094');
define('DB_PASS', '8myxWMIxh8');

define('SECRET_KEY', '4db85a8951c75ae2b0bce3dfd1aff683f301b2a1cbd84926e449f49fcda20594'); 
define('QR_EXPIRY_DEFAULT', 120);
define('UPLOAD_DIR', __DIR__ . '/uploads/');

try {
    $pdo = new PDO("mysql:host=".DB_HOST.";dbname=".DB_NAME.";charset=utf8mb4", DB_USER, DB_PASS);
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    $pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_ASSOC);
    $pdo->setAttribute(PDO::ATTR_EMULATE_PREPARES, false);
} catch (PDOException $e) {
    die("Koneksi Database Gagal.");
}
// 4. Helper: JSON Response (Untuk API)
function jsonResponse($data, $code = 200) {
    http_response_code($code);
    header('Content-Type: application/json');
    echo json_encode($data);
    exit;
}

// 5. Helper: Auth untuk API (Return JSON 401)
function requireAuth() {
    if (!isset($_SESSION['admin_logged_in']) || $_SESSION['admin_logged_in'] !== true) {
        if (strpos($_SERVER['REQUEST_URI'], '/api/') !== false) {
            jsonResponse(['status' => 'error', 'message' => 'Unauthorized'], 401);
        }
        // Fallback jika dipanggil di luar konteks
        header("Location: /index.php");
        exit;
    }
}

// 6. Helper: Auth untuk Halaman (Redirect User Friendly)
function requireAuthPage() {
    if (!isset($_SESSION['admin_logged_in']) || $_SESSION['admin_logged_in'] !== true) {
        // Jika belum login, arahkan ke Home
        header("Location: /index.php");
        exit;
    }
}
?>